
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.cesar31.audiogenerator.parser.playlist;

/** CUP generated class containing symbol constants. */
public class PlaylistParserSym {
  /* terminals */
  public static final int RBRACE = 13;
  public static final int LIST = 2;
  public static final int TRACKS = 6;
  public static final int ERROR = 18;
  public static final int NAME = 3;
  public static final int TRUE = 7;
  public static final int LBRACKET = 14;
  public static final int COLON = 10;
  public static final int LBRACE = 12;
  public static final int ID = 9;
  public static final int RBRACKET = 15;
  public static final int RANDOM = 4;
  public static final int COMMA = 11;
  public static final int SYM = 17;
  public static final int EOF = 0;
  public static final int CIRCULAR = 5;
  public static final int FALSE = 8;
  public static final int error = 1;
  public static final int STR = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LIST",
  "NAME",
  "RANDOM",
  "CIRCULAR",
  "TRACKS",
  "TRUE",
  "FALSE",
  "ID",
  "COLON",
  "COMMA",
  "LBRACE",
  "RBRACE",
  "LBRACKET",
  "RBRACKET",
  "STR",
  "SYM",
  "ERROR"
  };
}

