// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: playlist.flex

package com.cesar31.audiogenerator.parser.playlist;

import static com.cesar31.audiogenerator.parser.playlist.PlaylistParserSym.*;
import java_cup.runtime.Symbol;

import com.cesar31.audiogenerator.parser.Token;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class PlaylistLex implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u0100\1\u1100\1\u1200\1\u1300\1\u0100\1\u1400\1\u1500"+
    "\1\u1600\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u0100\1\u1c00"+
    "\1\u1d00\1\u1e00\2\u1f00\1\u2000\7\u1f00\1\u2100\1\u2200\1\u2300"+
    "\1\u1f00\1\u2400\1\u2500\2\u1f00\31\u0100\1\u2600\121\u0100\1\u2700"+
    "\4\u0100\1\u2800\1\u0100\1\u2900\1\u2a00\1\u2b00\1\u2c00\1\u2d00"+
    "\1\u2e00\53\u0100\1\u2f00\41\u1f00\1\u0100\1\u3000\1\u3100\1\u0100"+
    "\1\u3200\1\u3300\1\u3400\1\u3500\1\u3600\1\u3700\1\u3800\1\u3900"+
    "\1\u3a00\1\u0100\1\u3b00\1\u3c00\1\u3d00\1\u3e00\1\u3f00\1\u4000"+
    "\1\u4100\1\u1f00\1\u4200\1\u4300\1\u4400\1\u4500\1\u4600\1\u4700"+
    "\1\u4800\1\u4900\1\u4a00\1\u4b00\1\u4c00\1\u4d00\1\u1f00\1\u4e00"+
    "\1\u4f00\1\u5000\1\u1f00\3\u0100\1\u5100\1\u5200\1\u5300\12\u1f00"+
    "\4\u0100\1\u5400\17\u1f00\2\u0100\1\u5500\41\u1f00\2\u0100\1\u5600"+
    "\1\u5700\2\u1f00\1\u5800\1\u5900\27\u0100\1\u5a00\2\u0100\1\u5b00"+
    "\45\u1f00\1\u0100\1\u5c00\1\u5d00\11\u1f00\1\u5e00\24\u1f00\1\u5f00"+
    "\1\u6000\1\u1f00\1\u6100\1\u6200\1\u6300\1\u6400\2\u1f00\1\u6500"+
    "\5\u1f00\1\u6600\1\u6700\1\u6800\5\u1f00\1\u6900\1\u6a00\4\u1f00"+
    "\1\u6b00\2\u1f00\1\u6c00\16\u1f00\246\u0100\1\u6d00\20\u0100\1\u6e00"+
    "\1\u6f00\25\u0100\1\u7000\34\u0100\1\u7100\14\u1f00\2\u0100\1\u7200"+
    "\u0b06\u1f00\1\u2700\u02fe\u1f00";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\0\1\1\1\3\22\0\1\1"+
    "\1\4\1\5\11\4\1\6\3\4\12\7\1\10\1\4"+
    "\3\0\2\4\32\11\1\12\1\13\1\14\1\4\1\7"+
    "\1\4\1\15\1\16\1\17\1\20\1\21\1\22\2\11"+
    "\1\23\2\11\1\24\1\25\1\26\1\27\1\30\1\11"+
    "\1\31\1\32\1\33\1\34\5\11\1\35\1\4\1\36"+
    "\1\4\42\0\1\4\2\0\4\4\1\0\1\4\1\7"+
    "\2\4\1\0\1\4\1\0\1\4\1\0\3\4\1\7"+
    "\1\4\1\0\1\4\1\0\1\7\5\4\27\7\1\0"+
    "\37\7\1\0\u01ca\7\4\0\14\7\12\0\1\4\3\0"+
    "\5\7\7\0\1\7\1\0\1\7\21\0\165\7\1\0"+
    "\2\7\2\0\4\7\1\0\1\7\6\0\1\7\1\0"+
    "\3\7\1\0\1\7\1\0\24\7\1\0\123\7\1\0"+
    "\213\7\1\0\255\7\1\0\46\7\2\0\1\7\6\0"+
    "\51\7\10\0\55\7\1\0\1\7\1\0\2\7\1\0"+
    "\2\7\1\0\1\7\10\0\33\7\4\0\4\7\35\0"+
    "\13\7\5\0\112\7\4\0\146\7\1\0\10\7\2\0"+
    "\12\7\1\0\23\7\2\0\1\7\20\0\73\7\2\0"+
    "\145\7\16\0\66\7\4\0\1\7\2\0\1\7\2\0"+
    "\56\7\22\0\34\7\4\0\13\7\65\0\25\7\1\0"+
    "\10\7\25\0\17\7\1\0\201\7\2\0\12\7\1\0"+
    "\23\7\1\0\10\7\2\0\2\7\2\0\26\7\1\0"+
    "\7\7\1\0\1\7\3\0\4\7\2\0\11\7\2\0"+
    "\2\7\2\0\4\7\10\0\1\7\4\0\2\7\1\0"+
    "\5\7\2\0\14\7\12\0\1\7\1\0\1\7\2\0"+
    "\3\7\1\0\6\7\4\0\2\7\2\0\26\7\1\0"+
    "\7\7\1\0\2\7\1\0\2\7\1\0\2\7\2\0"+
    "\1\7\1\0\5\7\4\0\2\7\2\0\3\7\3\0"+
    "\1\7\7\0\4\7\1\0\1\7\7\0\20\7\13\0"+
    "\3\7\1\0\11\7\1\0\3\7\1\0\26\7\1\0"+
    "\7\7\1\0\2\7\1\0\5\7\2\0\12\7\1\0"+
    "\3\7\1\0\3\7\2\0\1\7\17\0\4\7\2\0"+
    "\12\7\11\0\7\7\1\0\3\7\1\0\10\7\2\0"+
    "\2\7\2\0\26\7\1\0\7\7\1\0\2\7\1\0"+
    "\5\7\2\0\11\7\2\0\2\7\2\0\3\7\10\0"+
    "\2\7\4\0\2\7\1\0\5\7\2\0\12\7\1\0"+
    "\1\7\20\0\2\7\1\0\6\7\3\0\3\7\1\0"+
    "\4\7\3\0\2\7\1\0\1\7\1\0\2\7\3\0"+
    "\2\7\3\0\3\7\3\0\14\7\4\0\5\7\3\0"+
    "\3\7\1\0\4\7\2\0\1\7\6\0\1\7\16\0"+
    "\12\7\20\0\15\7\1\0\3\7\1\0\27\7\1\0"+
    "\20\7\3\0\10\7\1\0\3\7\1\0\4\7\7\0"+
    "\2\7\1\0\3\7\5\0\4\7\2\0\12\7\20\0"+
    "\4\7\1\0\10\7\1\0\3\7\1\0\27\7\1\0"+
    "\12\7\1\0\5\7\2\0\11\7\1\0\3\7\1\0"+
    "\4\7\7\0\2\7\7\0\1\7\1\0\4\7\2\0"+
    "\12\7\1\0\2\7\15\0\4\7\1\0\10\7\1\0"+
    "\3\7\1\0\63\7\1\0\3\7\1\0\5\7\5\0"+
    "\4\7\7\0\5\7\2\0\12\7\12\0\6\7\2\0"+
    "\2\7\1\0\22\7\3\0\30\7\1\0\11\7\1\0"+
    "\1\7\2\0\7\7\3\0\1\7\4\0\6\7\1\0"+
    "\1\7\1\0\10\7\6\0\12\7\2\0\2\7\15\0"+
    "\72\7\5\0\17\7\1\0\12\7\47\0\2\7\1\0"+
    "\1\7\1\0\5\7\1\0\30\7\1\0\1\7\1\0"+
    "\27\7\2\0\5\7\1\0\1\7\1\0\6\7\2\0"+
    "\12\7\2\0\4\7\40\0\1\7\27\0\2\7\6\0"+
    "\12\7\13\0\1\7\1\0\1\7\1\0\1\7\4\0"+
    "\12\7\1\0\44\7\4\0\24\7\1\0\22\7\1\0"+
    "\44\7\11\0\1\7\71\0\112\7\6\0\116\7\2\0"+
    "\46\7\1\0\1\7\5\0\1\7\2\0\53\7\1\0"+
    "\115\7\1\0\4\7\2\0\7\7\1\0\1\7\1\0"+
    "\4\7\2\0\51\7\1\0\4\7\2\0\41\7\1\0"+
    "\4\7\2\0\7\7\1\0\1\7\1\0\4\7\2\0"+
    "\17\7\1\0\71\7\1\0\4\7\2\0\103\7\2\0"+
    "\3\7\40\0\20\7\20\0\126\7\2\0\6\7\3\0"+
    "\u016c\7\2\0\21\7\1\0\32\7\5\0\113\7\3\0"+
    "\13\7\7\0\15\7\1\0\7\7\13\0\25\7\13\0"+
    "\24\7\14\0\15\7\1\0\3\7\1\0\2\7\14\0"+
    "\124\7\3\0\1\7\4\0\2\7\2\0\12\7\41\0"+
    "\3\7\2\0\12\7\6\0\131\7\7\0\53\7\5\0"+
    "\106\7\12\0\37\7\1\0\14\7\4\0\14\7\12\0"+
    "\50\7\2\0\5\7\13\0\54\7\4\0\32\7\6\0"+
    "\12\7\46\0\34\7\4\0\77\7\1\0\35\7\2\0"+
    "\13\7\6\0\12\7\15\0\1\7\10\0\17\7\101\0"+
    "\114\7\4\0\12\7\21\0\11\7\14\0\164\7\14\0"+
    "\70\7\10\0\12\7\3\0\61\7\2\0\11\7\7\0"+
    "\53\7\2\0\3\7\20\0\3\7\1\0\47\7\5\0"+
    "\372\7\1\0\33\7\2\0\6\7\2\0\46\7\2\0"+
    "\6\7\2\0\10\7\1\0\1\7\1\0\1\7\1\0"+
    "\1\7\1\0\37\7\2\0\65\7\1\0\7\7\1\0"+
    "\1\7\3\0\3\7\1\0\7\7\3\0\4\7\2\0"+
    "\6\7\4\0\15\7\5\0\3\7\1\0\7\7\27\0"+
    "\1\4\5\0\1\4\44\0\2\7\23\0\1\7\34\0"+
    "\1\7\15\0\1\7\20\0\15\7\17\0\1\4\43\0"+
    "\41\7\21\0\1\7\4\0\1\7\2\0\12\7\1\0"+
    "\1\7\3\0\5\7\4\0\1\4\1\0\1\7\1\0"+
    "\1\7\1\0\1\7\1\0\4\7\1\0\13\7\2\0"+
    "\4\7\5\0\5\7\4\0\1\7\21\0\51\7\u022d\0"+
    "\64\7\26\0\57\7\1\0\57\7\1\0\205\7\6\0"+
    "\11\7\14\0\46\7\1\0\1\7\5\0\1\7\2\0"+
    "\70\7\7\0\1\7\17\0\30\7\11\0\7\7\1\0"+
    "\7\7\1\0\7\7\1\0\7\7\1\0\7\7\1\0"+
    "\7\7\1\0\7\7\1\0\7\7\1\0\40\7\57\0"+
    "\1\7\325\0\3\7\31\0\17\7\1\0\5\7\2\0"+
    "\5\7\4\0\126\7\2\0\2\7\2\0\3\7\1\0"+
    "\132\7\1\0\4\7\5\0\53\7\1\0\136\7\21\0"+
    "\33\7\65\0\306\7\112\0\360\7\20\0\215\7\103\0"+
    "\56\7\2\0\15\7\3\0\34\7\24\0\63\7\1\0"+
    "\12\7\1\0\163\7\45\0\11\7\2\0\147\7\2\0"+
    "\65\7\2\0\5\7\60\0\61\7\30\0\64\7\14\0"+
    "\106\7\12\0\12\7\6\0\30\7\3\0\1\7\1\0"+
    "\61\7\2\0\44\7\14\0\35\7\3\0\101\7\16\0"+
    "\13\7\6\0\37\7\1\0\67\7\11\0\16\7\2\0"+
    "\12\7\6\0\27\7\3\0\111\7\30\0\3\7\2\0"+
    "\20\7\2\0\5\7\12\0\6\7\2\0\6\7\2\0"+
    "\6\7\11\0\7\7\1\0\7\7\1\0\53\7\1\0"+
    "\14\7\10\0\173\7\1\0\2\7\2\0\12\7\6\0"+
    "\244\7\14\0\27\7\4\0\61\7\4\0\156\7\2\0"+
    "\152\7\46\0\7\7\14\0\5\7\5\0\14\7\1\0"+
    "\15\7\1\0\5\7\1\0\1\7\1\0\2\7\1\0"+
    "\2\7\1\0\154\7\41\0\153\7\22\0\100\7\2\0"+
    "\66\7\50\0\14\7\4\0\20\7\20\0\20\7\3\0"+
    "\2\7\30\0\3\7\40\0\5\7\1\0\207\7\23\0"+
    "\12\7\7\0\32\7\4\0\1\7\1\0\32\7\13\0"+
    "\131\7\3\0\6\7\2\0\6\7\2\0\6\7\2\0"+
    "\3\7\43\0\14\7\1\0\32\7\1\0\23\7\1\0"+
    "\2\7\1\0\17\7\2\0\16\7\42\0\173\7\105\0"+
    "\65\7\210\0\1\7\202\0\35\7\3\0\61\7\17\0"+
    "\1\7\37\0\40\7\15\0\36\7\5\0\53\7\5\0"+
    "\36\7\2\0\44\7\4\0\10\7\1\0\5\7\52\0"+
    "\236\7\2\0\12\7\6\0\44\7\4\0\44\7\4\0"+
    "\50\7\10\0\64\7\234\0\67\7\11\0\26\7\12\0"+
    "\10\7\230\0\6\7\2\0\1\7\1\0\54\7\1\0"+
    "\2\7\3\0\1\7\2\0\27\7\12\0\27\7\11\0"+
    "\37\7\101\0\23\7\1\0\2\7\12\0\26\7\12\0"+
    "\32\7\106\0\70\7\6\0\2\7\100\0\4\7\1\0"+
    "\2\7\5\0\10\7\1\0\3\7\1\0\35\7\2\0"+
    "\3\7\4\0\1\7\40\0\35\7\3\0\35\7\43\0"+
    "\10\7\1\0\36\7\31\0\66\7\12\0\26\7\12\0"+
    "\23\7\15\0\22\7\156\0\111\7\67\0\63\7\15\0"+
    "\63\7\15\0\50\7\10\0\12\7\306\0\35\7\12\0"+
    "\1\7\10\0\41\7\217\0\27\7\11\0\107\7\37\0"+
    "\12\7\17\0\74\7\25\0\31\7\7\0\12\7\6\0"+
    "\65\7\1\0\12\7\4\0\3\7\11\0\44\7\2\0"+
    "\1\7\11\0\105\7\4\0\4\7\3\0\13\7\1\0"+
    "\1\7\43\0\22\7\1\0\45\7\6\0\1\7\101\0"+
    "\7\7\1\0\1\7\1\0\4\7\1\0\17\7\1\0"+
    "\12\7\7\0\73\7\5\0\12\7\6\0\4\7\1\0"+
    "\10\7\2\0\2\7\2\0\26\7\1\0\7\7\1\0"+
    "\2\7\1\0\5\7\1\0\12\7\2\0\2\7\2\0"+
    "\3\7\2\0\1\7\6\0\1\7\5\0\7\7\2\0"+
    "\7\7\3\0\5\7\213\0\113\7\5\0\12\7\4\0"+
    "\2\7\40\0\106\7\1\0\1\7\10\0\12\7\246\0"+
    "\66\7\2\0\11\7\27\0\6\7\42\0\101\7\3\0"+
    "\1\7\13\0\12\7\46\0\71\7\7\0\12\7\66\0"+
    "\33\7\2\0\17\7\4\0\12\7\306\0\73\7\145\0"+
    "\112\7\25\0\1\7\240\0\10\7\2\0\56\7\2\0"+
    "\10\7\1\0\2\7\33\0\77\7\10\0\1\7\10\0"+
    "\112\7\3\0\1\7\42\0\71\7\7\0\11\7\1\0"+
    "\55\7\1\0\11\7\17\0\12\7\30\0\36\7\2\0"+
    "\26\7\1\0\16\7\111\0\7\7\1\0\2\7\1\0"+
    "\54\7\3\0\1\7\1\0\2\7\1\0\11\7\10\0"+
    "\12\7\6\0\6\7\1\0\2\7\1\0\45\7\1\0"+
    "\2\7\1\0\6\7\7\0\12\7\u0136\0\27\7\11\0"+
    "\232\7\146\0\157\7\21\0\304\7\274\0\57\7\321\0"+
    "\107\7\271\0\71\7\7\0\37\7\1\0\12\7\146\0"+
    "\36\7\2\0\5\7\13\0\67\7\11\0\4\7\14\0"+
    "\12\7\11\0\25\7\5\0\23\7\260\0\100\7\200\0"+
    "\113\7\4\0\71\7\7\0\21\7\100\0\2\7\1\0"+
    "\1\7\34\0\370\7\10\0\363\7\15\0\37\7\61\0"+
    "\3\7\21\0\4\7\10\0\u018c\7\4\0\153\7\5\0"+
    "\15\7\3\0\11\7\7\0\12\7\3\0\2\7\306\0"+
    "\5\7\3\0\6\7\10\0\10\7\2\0\7\7\36\0"+
    "\4\7\224\0\3\7\273\0\125\7\1\0\107\7\1\0"+
    "\2\7\2\0\1\7\2\0\2\7\2\0\4\7\1\0"+
    "\14\7\1\0\1\7\1\0\7\7\1\0\101\7\1\0"+
    "\4\7\2\0\10\7\1\0\7\7\1\0\34\7\1\0"+
    "\4\7\1\0\5\7\1\0\1\7\3\0\7\7\1\0"+
    "\u0154\7\2\0\31\7\1\0\31\7\1\0\37\7\1\0"+
    "\31\7\1\0\37\7\1\0\31\7\1\0\37\7\1\0"+
    "\31\7\1\0\37\7\1\0\31\7\1\0\10\7\2\0"+
    "\151\7\4\0\62\7\10\0\1\7\16\0\1\7\26\0"+
    "\5\7\1\0\17\7\120\0\7\7\1\0\21\7\2\0"+
    "\7\7\1\0\2\7\1\0\5\7\325\0\55\7\3\0"+
    "\16\7\2\0\12\7\4\0\1\7\u0171\0\72\7\6\0"+
    "\305\7\13\0\7\7\51\0\114\7\4\0\12\7\246\0"+
    "\4\7\1\0\33\7\1\0\2\7\1\0\1\7\2\0"+
    "\1\7\1\0\12\7\1\0\4\7\1\0\1\7\1\0"+
    "\1\7\6\0\1\7\4\0\1\7\1\0\1\7\1\0"+
    "\1\7\1\0\3\7\1\0\2\7\1\0\1\7\2\0"+
    "\1\7\1\0\1\7\1\0\1\7\1\0\1\7\1\0"+
    "\1\7\1\0\2\7\1\0\1\7\2\0\4\7\1\0"+
    "\7\7\1\0\4\7\1\0\4\7\1\0\1\7\1\0"+
    "\12\7\1\0\21\7\5\0\3\7\1\0\5\7\1\0"+
    "\21\7\164\0\32\7\6\0\32\7\6\0\32\7\166\0"+
    "\327\7\51\0\65\7\13\0\336\7\2\0\u0182\7\16\0"+
    "\u0131\7\37\0\36\7\342\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[29440];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\7\7\1\12\1\13\1\14\1\15\1\16"+
    "\7\7\1\17\1\20\1\21\1\22\15\7\1\23\1\7"+
    "\1\24\1\25\4\7\1\26\1\27\1\30\1\7\1\31";

  private static int [] zzUnpackAction() {
    int [] result = new int[61];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\37\0\76\0\76\0\135\0\174\0\76\0\76"+
    "\0\76\0\233\0\76\0\76\0\272\0\331\0\370\0\u0117"+
    "\0\u0136\0\u0155\0\u0174\0\76\0\76\0\u0193\0\76\0\u01b2"+
    "\0\u01d1\0\u01f0\0\u020f\0\u022e\0\u024d\0\u026c\0\u028b\0\76"+
    "\0\76\0\76\0\76\0\u02aa\0\u02c9\0\u02e8\0\u0307\0\u0326"+
    "\0\u0345\0\u0364\0\u0383\0\u03a2\0\u03c1\0\u03e0\0\u03ff\0\u041e"+
    "\0\233\0\u043d\0\233\0\233\0\u045c\0\u047b\0\u049a\0\u04b9"+
    "\0\233\0\233\0\233\0\u04d8\0\233";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[61];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\5\1\6\1\7\1\10\1\6\1\11"+
    "\1\12\1\13\1\6\1\14\2\12\1\15\2\12\1\16"+
    "\1\12\1\17\1\12\1\20\1\12\1\21\1\22\1\12"+
    "\1\23\1\12\1\24\1\25\2\26\2\3\1\26\1\27"+
    "\5\26\1\30\23\26\41\0\1\4\40\0\1\6\2\0"+
    "\1\6\1\0\1\6\1\0\1\6\1\0\20\6\6\0"+
    "\1\6\2\0\1\12\1\0\1\12\1\0\1\6\1\0"+
    "\20\12\6\0\1\6\2\0\1\12\1\0\1\12\1\0"+
    "\1\6\1\0\6\12\1\31\11\12\6\0\1\6\2\0"+
    "\1\12\1\0\1\12\1\0\1\6\1\0\1\32\17\12"+
    "\6\0\1\6\2\0\1\12\1\0\1\12\1\0\1\6"+
    "\1\0\6\12\1\33\11\12\6\0\1\6\2\0\1\12"+
    "\1\0\1\12\1\0\1\6\1\0\12\12\1\34\5\12"+
    "\6\0\1\6\2\0\1\12\1\0\1\12\1\0\1\6"+
    "\1\0\6\12\1\35\11\12\6\0\1\6\2\0\1\12"+
    "\1\0\1\12\1\0\1\6\1\0\1\36\17\12\6\0"+
    "\1\6\2\0\1\12\1\0\1\12\1\0\1\6\1\0"+
    "\14\12\1\37\3\12\2\0\2\26\2\0\1\26\1\0"+
    "\5\26\1\0\23\26\5\0\1\40\20\0\1\41\2\0"+
    "\1\42\1\0\1\43\7\0\1\6\2\0\1\12\1\0"+
    "\1\12\1\0\1\6\1\0\14\12\1\44\3\12\6\0"+
    "\1\6\2\0\1\12\1\0\1\12\1\0\1\6\1\0"+
    "\7\12\1\45\10\12\6\0\1\6\2\0\1\12\1\0"+
    "\1\12\1\0\1\6\1\0\15\12\1\46\2\12\6\0"+
    "\1\6\2\0\1\12\1\0\1\12\1\0\1\6\1\0"+
    "\10\12\1\47\7\12\6\0\1\6\2\0\1\12\1\0"+
    "\1\12\1\0\1\6\1\0\15\12\1\50\2\12\6\0"+
    "\1\6\2\0\1\12\1\0\1\12\1\0\1\6\1\0"+
    "\11\12\1\51\6\12\6\0\1\6\2\0\1\12\1\0"+
    "\1\12\1\0\1\6\1\0\17\12\1\52\6\0\1\6"+
    "\2\0\1\12\1\0\1\12\1\0\1\6\1\0\2\12"+
    "\1\53\15\12\6\0\1\6\2\0\1\12\1\0\1\12"+
    "\1\0\1\6\1\0\15\12\1\54\2\12\6\0\1\6"+
    "\2\0\1\12\1\0\1\12\1\0\1\6\1\0\16\12"+
    "\1\55\1\12\6\0\1\6\2\0\1\12\1\0\1\12"+
    "\1\0\1\6\1\0\1\12\1\56\16\12\6\0\1\6"+
    "\2\0\1\12\1\0\1\12\1\0\1\6\1\0\16\12"+
    "\1\57\1\12\6\0\1\6\2\0\1\12\1\0\1\12"+
    "\1\0\1\6\1\0\3\12\1\60\14\12\6\0\1\6"+
    "\2\0\1\12\1\0\1\12\1\0\1\6\1\0\4\12"+
    "\1\61\13\12\6\0\1\6\2\0\1\12\1\0\1\12"+
    "\1\0\1\6\1\0\17\12\1\62\6\0\1\6\2\0"+
    "\1\12\1\0\1\12\1\0\1\6\1\0\4\12\1\63"+
    "\13\12\6\0\1\6\2\0\1\12\1\0\1\12\1\0"+
    "\1\6\1\0\1\64\17\12\6\0\1\6\2\0\1\12"+
    "\1\0\1\12\1\0\1\6\1\0\14\12\1\65\3\12"+
    "\6\0\1\6\2\0\1\12\1\0\1\12\1\0\1\6"+
    "\1\0\1\66\17\12\6\0\1\6\2\0\1\12\1\0"+
    "\1\12\1\0\1\6\1\0\12\12\1\67\5\12\6\0"+
    "\1\6\2\0\1\12\1\0\1\12\1\0\1\6\1\0"+
    "\7\12\1\70\10\12\6\0\1\6\2\0\1\12\1\0"+
    "\1\12\1\0\1\6\1\0\4\12\1\71\13\12\6\0"+
    "\1\6\2\0\1\12\1\0\1\12\1\0\1\6\1\0"+
    "\15\12\1\72\2\12\6\0\1\6\2\0\1\12\1\0"+
    "\1\12\1\0\1\6\1\0\10\12\1\73\7\12\6\0"+
    "\1\6\2\0\1\12\1\0\1\12\1\0\1\6\1\0"+
    "\1\74\17\12\6\0\1\6\2\0\1\12\1\0\1\12"+
    "\1\0\1\6\1\0\14\12\1\75\3\12\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1271];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\2\11\2\1\3\11\1\1\2\11\7\1\2\11"+
    "\1\1\1\11\10\1\4\11\32\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[61];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
	StringBuffer string = new StringBuffer();

	private Symbol symbol(int type) {
		return new Symbol(type, yyline + 1, yycolumn + 1, new Token(type, yyline + 1, yycolumn + 1));
		// return new Symbol(type, yyline + 1, yycolumn + 1);
	}

	private Symbol symbol(int type, Object object) {
		return new Symbol(type, yyline + 1, yycolumn + 1, new Token(type, (String) object, yyline + 1, yycolumn + 1));
		// return new Symbol(type, yyline + 1, yycolumn + 1, object);
	}


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public PlaylistLex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { 	return symbol(EOF);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.out.println("Error: < " + yytext() + " >");
	return symbol(ERROR, yytext());
            }
            // fall through
          case 26: break;
          case 2:
            { /* Ignore */
            }
            // fall through
          case 27: break;
          case 3:
            { return symbol(SYM, yytext());
            }
            // fall through
          case 28: break;
          case 4:
            { string.setLength(0);
        yybegin(STRING);
            }
            // fall through
          case 29: break;
          case 5:
            { return symbol(COMMA, yytext());
            }
            // fall through
          case 30: break;
          case 6:
            { return symbol(COLON, yytext());
            }
            // fall through
          case 31: break;
          case 7:
            { return symbol(ID, yytext());
            }
            // fall through
          case 32: break;
          case 8:
            { return symbol(LBRACKET, yytext());
            }
            // fall through
          case 33: break;
          case 9:
            { return symbol(RBRACKET, yytext());
            }
            // fall through
          case 34: break;
          case 10:
            { return symbol(LBRACE, yytext());
            }
            // fall through
          case 35: break;
          case 11:
            { return symbol(RBRACE, yytext());
            }
            // fall through
          case 36: break;
          case 12:
            { string.append(yytext());
            }
            // fall through
          case 37: break;
          case 13:
            { yybegin(YYINITIAL);
        return symbol(STR, string.toString());
            }
            // fall through
          case 38: break;
          case 14:
            { string.append('\\');
            }
            // fall through
          case 39: break;
          case 15:
            { string.append('\"');
            }
            // fall through
          case 40: break;
          case 16:
            { string.append('\n');
            }
            // fall through
          case 41: break;
          case 17:
            { string.append('\r');
            }
            // fall through
          case 42: break;
          case 18:
            { string.append('\t');
            }
            // fall through
          case 43: break;
          case 19:
            { return symbol(TRUE, yytext());
            }
            // fall through
          case 44: break;
          case 20:
            { return symbol(FALSE, yytext());
            }
            // fall through
          case 45: break;
          case 21:
            { return symbol(LIST, yytext());
            }
            // fall through
          case 46: break;
          case 22:
            { return symbol(NAME, yytext());
            }
            // fall through
          case 47: break;
          case 23:
            { return symbol(TRACKS, yytext());
            }
            // fall through
          case 48: break;
          case 24:
            { return symbol(RANDOM, yytext());
            }
            // fall through
          case 49: break;
          case 25:
            { return symbol(CIRCULAR, yytext());
            }
            // fall through
          case 50: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
