
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.cesar31.audiogeneratorclient.parser;

import com.cesar31.audiogeneratorclient.model.*;
import java_cup.runtime.Symbol;
import java.util.ArrayList;
import java.util.List;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class ClientParser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return ClientParserSym.class;
}

  /** Default constructor. */
  @Deprecated
  public ClientParser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public ClientParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ClientParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\077\000\002\065\003\000\002\002\004\000\002\065" +
    "\003\000\002\065\003\000\002\065\003\000\002\065\003" +
    "\000\002\021\005\000\002\064\006\000\002\037\004\000" +
    "\002\037\003\000\002\036\005\000\002\035\004\000\002" +
    "\035\003\000\002\012\006\000\002\063\006\000\002\011" +
    "\005\000\002\034\010\000\002\006\005\000\002\031\005" +
    "\000\002\062\006\000\002\033\005\000\002\032\004\000" +
    "\002\032\003\000\002\030\011\000\002\024\005\000\002" +
    "\025\005\000\002\026\005\000\002\027\003\000\002\027" +
    "\003\000\002\060\005\000\002\061\006\000\002\023\005" +
    "\000\002\022\004\000\002\022\003\000\002\020\007\000" +
    "\002\005\005\000\002\017\005\000\002\056\005\000\002" +
    "\057\006\000\002\016\005\000\002\015\004\000\002\015" +
    "\003\000\002\014\005\000\002\013\007\000\002\002\005" +
    "\000\002\007\005\000\002\010\005\000\002\003\005\000" +
    "\002\004\005\000\002\040\005\000\002\041\005\000\002" +
    "\042\005\000\002\043\005\000\002\044\005\000\002\045" +
    "\005\000\002\046\005\000\002\047\006\000\002\050\006" +
    "\000\002\051\006\000\002\052\006\000\002\053\006\000" +
    "\002\054\006\000\002\055\006" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\261\000\004\033\005\001\002\000\004\002\ufffe\001" +
    "\002\000\014\004\260\014\257\015\063\020\256\021\023" +
    "\001\002\000\004\033\216\001\002\000\004\033\056\001" +
    "\002\000\004\002\206\001\002\000\004\033\076\001\002" +
    "\000\004\002\ufffd\001\002\000\004\033\056\001\002\000" +
    "\004\002\001\001\002\000\004\002\uffff\001\002\000\004" +
    "\033\022\001\002\000\004\002\ufffc\001\002\000\004\033" +
    "\uffeb\001\002\000\004\033\050\001\002\000\004\021\023" +
    "\001\002\000\004\016\025\001\002\000\004\014\030\001" +
    "\002\000\004\032\026\001\002\000\004\040\027\001\002" +
    "\000\010\014\uffde\017\uffde\031\uffde\001\002\000\004\032" +
    "\045\001\002\000\004\022\032\001\002\000\004\032\043" +
    "\001\002\000\004\023\034\001\002\000\004\032\037\001" +
    "\002\000\004\034\036\001\002\000\004\033\uffea\001\002" +
    "\000\006\024\041\025\042\001\002\000\004\034\uffe7\001" +
    "\002\000\006\023\uffe6\034\uffe6\001\002\000\006\023\uffe5" +
    "\034\uffe5\001\002\000\006\024\041\025\042\001\002\000" +
    "\004\023\uffe8\001\002\000\004\036\046\001\002\000\004" +
    "\022\uffe9\001\002\000\004\033\uffec\001\002\000\006\021" +
    "\023\035\052\001\002\000\004\002\uffed\001\002\000\004" +
    "\020\053\001\002\000\004\034\054\001\002\000\004\002" +
    "\uffe3\001\002\000\004\033\uffe0\001\002\000\004\015\063" +
    "\001\002\000\004\033\062\001\002\000\004\033\uffe1\001" +
    "\002\000\004\002\uffef\001\002\000\006\015\063\035\064" +
    "\001\002\000\004\016\025\001\002\000\004\021\065\001" +
    "\002\000\004\034\066\001\002\000\004\002\uffee\001\002" +
    "\000\004\017\070\001\002\000\004\032\073\001\002\000" +
    "\004\034\072\001\002\000\004\033\uffdf\001\002\000\004" +
    "\037\074\001\002\000\004\034\uffdd\001\002\000\004\033" +
    "\202\001\002\000\004\005\176\001\002\000\004\033\uffd8" +
    "\001\002\000\004\033\103\001\002\000\004\033\172\001" +
    "\002\000\004\033\117\001\002\000\004\006\113\001\002" +
    "\000\004\007\105\001\002\000\004\033\107\001\002\000" +
    "\004\033\uffd5\001\002\000\004\035\110\001\002\000\004" +
    "\006\111\001\002\000\004\034\112\001\002\000\004\033" +
    "\uffc9\001\002\000\004\034\114\001\002\000\004\007\uffd0" +
    "\001\002\000\004\033\132\001\002\000\004\036\122\001" +
    "\002\000\004\010\120\001\002\000\004\034\121\001\002" +
    "\000\004\036\uffcf\001\002\000\004\033\123\001\002\000" +
    "\004\035\125\001\002\000\004\033\uffd4\001\002\000\004" +
    "\010\126\001\002\000\004\034\127\001\002\000\004\033" +
    "\uffc8\001\002\000\004\036\163\001\002\000\004\033\137" +
    "\001\002\000\004\011\133\001\002\000\004\034\134\001" +
    "\002\000\004\036\uffce\001\002\000\004\033\151\001\002" +
    "\000\004\040\142\001\002\000\004\012\140\001\002\000" +
    "\004\034\141\001\002\000\004\040\uffcd\001\002\000\004" +
    "\033\144\001\002\000\004\033\uffd2\001\002\000\004\035" +
    "\145\001\002\000\004\012\146\001\002\000\004\034\147" +
    "\001\002\000\004\033\uffc6\001\002\000\004\040\155\001" +
    "\002\000\004\013\153\001\002\000\004\033\uffd6\001\002" +
    "\000\004\034\154\001\002\000\004\040\uffcc\001\002\000" +
    "\004\033\157\001\002\000\004\033\uffd1\001\002\000\004" +
    "\035\160\001\002\000\004\013\161\001\002\000\004\034" +
    "\162\001\002\000\004\033\uffc5\001\002\000\004\033\164" +
    "\001\002\000\004\035\166\001\002\000\004\033\uffd3\001" +
    "\002\000\004\011\167\001\002\000\004\034\170\001\002" +
    "\000\004\033\uffc7\001\002\000\004\033\uffd7\001\002\000" +
    "\004\035\173\001\002\000\004\005\174\001\002\000\004" +
    "\034\175\001\002\000\004\033\uffc4\001\002\000\004\034" +
    "\177\001\002\000\004\033\uffcb\001\002\000\004\002\uffda" +
    "\001\002\000\004\033\uffd9\001\002\000\006\005\176\035" +
    "\203\001\002\000\004\004\204\001\002\000\004\034\205" +
    "\001\002\000\004\002\uffc3\001\002\000\004\002\000\001" +
    "\002\000\004\033\210\001\002\000\006\015\063\035\212" +
    "\001\002\000\004\002\uffe2\001\002\000\004\014\213\001" +
    "\002\000\004\034\214\001\002\000\004\002\uffdb\001\002" +
    "\000\004\033\ufff8\001\002\000\004\026\224\001\002\000" +
    "\004\033\237\001\002\000\004\033\223\001\002\000\004" +
    "\002\ufffb\001\002\000\004\033\ufff9\001\002\000\006\026" +
    "\224\035\225\001\002\000\004\030\230\001\002\000\004" +
    "\015\226\001\002\000\004\034\227\001\002\000\004\002" +
    "\ufffa\001\002\000\004\032\233\001\002\000\004\034\232" +
    "\001\002\000\004\033\ufff4\001\002\000\004\036\234\001" +
    "\002\000\004\034\ufff2\001\002\000\004\033\251\001\002" +
    "\000\004\033\ufff5\001\002\000\004\027\240\001\002\000" +
    "\004\016\025\001\002\000\004\031\242\001\002\000\004" +
    "\032\246\001\002\000\004\017\070\001\002\000\004\034" +
    "\245\001\002\000\004\033\ufff1\001\002\000\004\040\247" +
    "\001\002\000\004\017\ufff0\001\002\000\004\033\ufff6\001" +
    "\002\000\006\027\240\035\253\001\002\000\004\033\ufff7" +
    "\001\002\000\004\026\254\001\002\000\004\034\255\001" +
    "\002\000\004\033\ufff3\001\002\000\004\034\263\001\002" +
    "\000\004\034\262\001\002\000\004\034\261\001\002\000" +
    "\004\033\uffca\001\002\000\004\033\uffdc\001\002\000\004" +
    "\033\uffe4\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\261\000\030\016\016\020\005\021\011\023\014\030" +
    "\012\031\003\033\013\046\010\056\006\060\015\065\007" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\012" +
    "\216\036\214\037\217\001\001\000\006\020\054\022\206" +
    "\001\001\000\002\001\001\000\010\014\076\015\074\045" +
    "\077\001\001\000\002\001\001\000\006\020\054\022\056" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\030" +
    "\017\032\020\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\030\046\061\050\001\001\000\002\001\001\000" +
    "\004\005\023\001\001\000\004\024\030\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\025\032\001\001\000\002\001\001\000\004" +
    "\026\034\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\027\037\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\027\043\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\020\057\062\060\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\005\066\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\017\070\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\014\200\045\077\055\177" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\002" +
    "\101\013\100\040\103\001\001\000\004\054\170\001\001" +
    "\000\006\007\114\041\115\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\047\105\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\010\130\042\127\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\050\123" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\003\134\043\135\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\004\151\044\147" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\052\142\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\053\155\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\051\164\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\020\057\057\210\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\034\235\035\234\001\001\000\010\012\216\036" +
    "\221\064\220\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\011\230\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\034\247\063\251\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\005\240\001\001\000" +
    "\004\006\242\001\001\000\002\001\001\000\004\017\243" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ClientParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ClientParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ClientParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    private List<Err> errors; // Errores
    private List<Track> tracks; // listado de pistas
    private List<Playlist> playlists; // listado de listas
    private Playlist playlist; // playlist con listado de pistas
    private Track track; // pista con sus respectivas notas

    public ClientParser(ClientLex lex) {
        super(lex);
    }

    public Track getTrack() {
        return track;
    }

    public Playlist getPlaylist() {
        return playlist;
    }

    public List<Playlist> getPlaylists() {
        return playlists;
    }

    public List<Track> getTracks() {
        return tracks;
    }

    public List<Err> getErrors() {
        return errors;
    }

    public void syntax_error(Symbol cur_token) {
		List<String> expected = new ArrayList<>();
		List<Integer> tokens = expected_token_ids();

		System.out.printf("Se encontro: %s -> (%s), linea %d columna %d, se esperaba -> ", cur_token.value, symbl_name_from_id(cur_token.sym), cur_token.left, cur_token.right);
		for(Integer i : tokens) {
			expected.add(symbl_name_from_id(i));
			System.out.printf("%s, ", symbl_name_from_id(i));
		}
        System.out.println();
        //this.errorHandler.setErrorForListGram((Token) cur_token.value, symbl_name_from_id(cur_token.sym), expected);
	}

	public void report_fatal_error(String message, Object info) {
		System.out.println("message: " + message);
		System.out.println("info: " + info);
	}

    protected int error_sync_size() {
        return 1;
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$ClientParser$actions {
  private final ClientParser parser;

  /** Constructor */
  CUP$ClientParser$actions(ClientParser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$ClientParser$do_action_part00000000(
    int                        CUP$ClientParser$act_num,
    java_cup.runtime.lr_parser CUP$ClientParser$parser,
    java.util.Stack            CUP$ClientParser$stack,
    int                        CUP$ClientParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ClientParser$result;

      /* select the action based on the action number */
      switch (CUP$ClientParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // client ::= list 
            {
              Object RESULT =null;
		int list_listleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()).left;
		int list_listright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()).right;
		List<Playlist> list_list = (List<Playlist>)((java_cup.runtime.Symbol) CUP$ClientParser$stack.peek()).value;
		 playlists = list_list; 
              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("client",51, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= client EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).value;
		RESULT = start_val;
              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ClientParser$parser.done_parsing();
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // client ::= tracks 
            {
              Object RESULT =null;
		int list_trackleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()).left;
		int list_trackright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()).right;
		List<Track> list_track = (List<Track>)((java_cup.runtime.Symbol) CUP$ClientParser$stack.peek()).value;
		 tracks = list_track; 
              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("client",51, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // client ::= list_tracks 
            {
              Object RESULT =null;
		int playleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()).left;
		int playright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()).right;
		Playlist play = (Playlist)((java_cup.runtime.Symbol) CUP$ClientParser$stack.peek()).value;
		 playlist = play; 
              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("client",51, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // client ::= track_notes 
            {
              Object RESULT =null;
		int track_notesleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()).left;
		int track_notesright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()).right;
		Track track_notes = (Track)((java_cup.runtime.Symbol) CUP$ClientParser$stack.peek()).value;
		 track = track_notes; 
              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("client",51, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // client ::= errors 
            {
              Object RESULT =null;
		int list_errleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()).left;
		int list_errright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()).right;
		List<Err> list_err = (List<Err>)((java_cup.runtime.Symbol) CUP$ClientParser$stack.peek()).value;
		 errors = list_err; 
              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("client",51, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // track_notes ::= track list_channel cl_track 
            {
              Track RESULT =null;
		int trackleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)).left;
		int trackright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)).right;
		Track track = (Track)((java_cup.runtime.Symbol) CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)).value;
		int list_notesleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).left;
		int list_notesright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).right;
		List<Note> list_notes = (List<Note>)((java_cup.runtime.Symbol) CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).value;
		 RESULT = track; RESULT.setNotes(list_notes); 
              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("track_notes",15, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // cl_track ::= SMALLER DIVIDE TRACK GREATER 
            {
              Object RESULT =null;

              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("cl_track",50, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-3)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // list_channel ::= list_channel channel 
            {
              List<Note> RESULT =null;
		int sup_listleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).left;
		int sup_listright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).right;
		List<Note> sup_list = (List<Note>)((java_cup.runtime.Symbol) CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()).right;
		List<Note> list = (List<Note>)((java_cup.runtime.Symbol) CUP$ClientParser$stack.peek()).value;
		 RESULT = sup_list; RESULT.addAll(list); 
              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("list_channel",29, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // list_channel ::= channel 
            {
              List<Note> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()).right;
		List<Note> list = (List<Note>)((java_cup.runtime.Symbol) CUP$ClientParser$stack.peek()).value;
		 RESULT = list; 
              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("list_channel",29, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // channel ::= op_channel list_notes cl_channel 
            {
              List<Note> RESULT =null;
		int numb_channelleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)).left;
		int numb_channelright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)).right;
		Integer numb_channel = (Integer)((java_cup.runtime.Symbol) CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).right;
		List<Note> list = (List<Note>)((java_cup.runtime.Symbol) CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).value;
		
                    for(Note n : list) {
                        n.setChannel(numb_channel);
                    }
                    RESULT = list;
                
              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("channel",28, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // list_notes ::= list_notes note 
            {
              List<Note> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).right;
		List<Note> list = (List<Note>)((java_cup.runtime.Symbol) CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).value;
		int noteleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()).left;
		int noteright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()).right;
		Note note = (Note)((java_cup.runtime.Symbol) CUP$ClientParser$stack.peek()).value;
		 RESULT = list; RESULT.add(note); 
              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("list_notes",27, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // list_notes ::= note 
            {
              List<Note> RESULT =null;
		int noteleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()).left;
		int noteright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()).right;
		Note note = (Note)((java_cup.runtime.Symbol) CUP$ClientParser$stack.peek()).value;
		 RESULT = new ArrayList<>(); RESULT.add(note); 
              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("list_notes",27, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // op_channel ::= SMALLER CHANNEL number GREATER 
            {
              Integer RESULT =null;
		int numberleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).left;
		int numberright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).right;
		Integer number = (Integer)((java_cup.runtime.Symbol) CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).value;
		 RESULT = number; 
              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("op_channel",8, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-3)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // cl_channel ::= SMALLER DIVIDE CHANNEL GREATER 
            {
              Object RESULT =null;

              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("cl_channel",49, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-3)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // number ::= NUMBER EQUAL INTEGER 
            {
              Integer RESULT =null;
		int tokenleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()).left;
		int tokenright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()).right;
		Token token = (Token)((java_cup.runtime.Symbol) CUP$ClientParser$stack.peek()).value;
		 RESULT = Integer.valueOf(token.getValue()); 
              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("number",7, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // note ::= SMALLER NOTE name eighth duration GREATER 
            {
              Note RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-3)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-3)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-3)).value;
		int eighthleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)).left;
		int eighthright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)).right;
		String eighth = (String)((java_cup.runtime.Symbol) CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)).value;
		int durationleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).left;
		int durationright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).right;
		Double duration = (Double)((java_cup.runtime.Symbol) CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).value;
		 RESULT = new Note(name, eighth, duration); 
              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("note",26, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-5)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // eighth ::= EIGHTH EQUAL STR 
            {
              String RESULT =null;
		int tokenleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()).left;
		int tokenright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()).right;
		Token token = (Token)((java_cup.runtime.Symbol) CUP$ClientParser$stack.peek()).value;
		 RESULT = token.getValue(); 
              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("eighth",4, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // list_tracks ::= list_item track_list cl_list 
            {
              Playlist RESULT =null;
		int playlistleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)).left;
		int playlistright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)).right;
		Playlist playlist = (Playlist)((java_cup.runtime.Symbol) CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)).value;
		int tracklistleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).left;
		int tracklistright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).right;
		List<Track> tracklist = (List<Track>)((java_cup.runtime.Symbol) CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).value;
		 RESULT = playlist; RESULT.setTracks(tracklist); 
              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("list_tracks",23, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // cl_list ::= SMALLER DIVIDE LIST GREATER 
            {
              Object RESULT =null;

              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("cl_list",48, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-3)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // list ::= op_lists list_list cl_lists 
            {
              List<Playlist> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).right;
		List<Playlist> list = (List<Playlist>)((java_cup.runtime.Symbol) CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).value;
		 RESULT = list; 
              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("list",25, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // list_list ::= list_list list_item 
            {
              List<Playlist> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).right;
		List<Playlist> list = (List<Playlist>)((java_cup.runtime.Symbol) CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).value;
		int playleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()).left;
		int playright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()).right;
		Playlist play = (Playlist)((java_cup.runtime.Symbol) CUP$ClientParser$stack.peek()).value;
		 RESULT = list; RESULT.add(play); 
              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("list_list",24, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // list_list ::= list_item 
            {
              List<Playlist> RESULT =null;
		int playleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()).left;
		int playright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()).right;
		Playlist play = (Playlist)((java_cup.runtime.Symbol) CUP$ClientParser$stack.peek()).value;
		 RESULT = new ArrayList<>(); RESULT.add(play); 
              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("list_list",24, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // list_item ::= SMALLER LIST name number_tracks random circular GREATER 
            {
              Playlist RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-4)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-4)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-4)).value;
		int numberleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-3)).left;
		int numberright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-3)).right;
		Integer number = (Integer)((java_cup.runtime.Symbol) CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-3)).value;
		int randomleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)).left;
		int randomright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)).right;
		Boolean random = (Boolean)((java_cup.runtime.Symbol) CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)).value;
		int circularleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).left;
		int circularright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).right;
		Boolean circular = (Boolean)((java_cup.runtime.Symbol) CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).value;
		 RESULT = new Playlist(name, number, random, circular); 
              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("list_item",22, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-6)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // number_tracks ::= TRACKS EQUAL INTEGER 
            {
              Integer RESULT =null;
		int tokenleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()).left;
		int tokenright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()).right;
		Token token = (Token)((java_cup.runtime.Symbol) CUP$ClientParser$stack.peek()).value;
		 RESULT = Integer.valueOf(token.getValue()); 
              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("number_tracks",18, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // random ::= RANDOM EQUAL boolean_value 
            {
              Boolean RESULT =null;
		int valueleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()).right;
		Boolean value = (Boolean)((java_cup.runtime.Symbol) CUP$ClientParser$stack.peek()).value;
		 RESULT = value; 
              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("random",19, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // circular ::= CIRCULAR EQUAL boolean_value 
            {
              Boolean RESULT =null;
		int valueleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()).right;
		Boolean value = (Boolean)((java_cup.runtime.Symbol) CUP$ClientParser$stack.peek()).value;
		 RESULT = value; 
              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("circular",20, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // boolean_value ::= TRUE 
            {
              Boolean RESULT =null;
		 RESULT = true; 
              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("boolean_value",21, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // boolean_value ::= FALSE 
            {
              Boolean RESULT =null;
		 RESULT = false; 
              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("boolean_value",21, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // op_lists ::= SMALLER LISTS GREATER 
            {
              Object RESULT =null;

              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("op_lists",46, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // cl_lists ::= SMALLER DIVIDE LISTS GREATER 
            {
              Object RESULT =null;

              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("cl_lists",47, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-3)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // tracks ::= op_tracks track_list cl_tracks 
            {
              List<Track> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).right;
		List<Track> list = (List<Track>)((java_cup.runtime.Symbol) CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).value;
		 RESULT = list; 
              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("tracks",17, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // track_list ::= track_list track 
            {
              List<Track> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).right;
		List<Track> list = (List<Track>)((java_cup.runtime.Symbol) CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).value;
		int trackleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()).left;
		int trackright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()).right;
		Track track = (Track)((java_cup.runtime.Symbol) CUP$ClientParser$stack.peek()).value;
		 RESULT = list; RESULT.add(track); 
              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("track_list",16, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // track_list ::= track 
            {
              List<Track> RESULT =null;
		int trackleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()).left;
		int trackright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()).right;
		Track track = (Track)((java_cup.runtime.Symbol) CUP$ClientParser$stack.peek()).value;
		 RESULT = new ArrayList<>(); RESULT.add(track); 
              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("track_list",16, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // track ::= SMALLER TRACK name duration GREATER 
            {
              Track RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)).value;
		int durationleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).left;
		int durationright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).right;
		Double duration = (Double)((java_cup.runtime.Symbol) CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).value;
		 RESULT = new Track(name, duration); 
              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("track",14, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-4)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // name ::= NAME EQUAL STR 
            {
              String RESULT =null;
		int tokenleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()).left;
		int tokenright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()).right;
		Token token = (Token)((java_cup.runtime.Symbol) CUP$ClientParser$stack.peek()).value;
		 RESULT = token.getValue(); 
              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("name",3, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // duration ::= DURATION EQUAL DECIMAL 
            {
              Double RESULT =null;
		int tokenleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()).left;
		int tokenright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()).right;
		Token token = (Token)((java_cup.runtime.Symbol) CUP$ClientParser$stack.peek()).value;
		 RESULT = Double.valueOf(token.getValue()); 
              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("duration",13, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // op_tracks ::= SMALLER TRACKS GREATER 
            {
              Object RESULT =null;

              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("op_tracks",44, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // cl_tracks ::= SMALLER DIVIDE TRACKS GREATER 
            {
              Object RESULT =null;

              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("cl_tracks",45, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-3)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // errors ::= op_errors error_list cl_errors 
            {
              List<Err> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).right;
		List<Err> list = (List<Err>)((java_cup.runtime.Symbol) CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).value;
		 RESULT = list; 
              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("errors",12, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // error_list ::= error_list err 
            {
              List<Err> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).right;
		List<Err> list = (List<Err>)((java_cup.runtime.Symbol) CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()).right;
		Err e = (Err)((java_cup.runtime.Symbol) CUP$ClientParser$stack.peek()).value;
		 RESULT = list; RESULT.add(e); 
              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("error_list",11, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // error_list ::= err 
            {
              List<Err> RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()).right;
		Err e = (Err)((java_cup.runtime.Symbol) CUP$ClientParser$stack.peek()).value;
		 RESULT = new ArrayList<>(); RESULT.add(e); 
              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("error_list",11, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // err ::= op_error error_options cl_error 
            {
              Err RESULT =null;
		int errleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).left;
		int errright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).right;
		Err err = (Err)((java_cup.runtime.Symbol) CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).value;
		 RESULT = err; 
              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("err",10, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // error_options ::= type line column lex desc 
            {
              Err RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-4)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-4)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-4)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-3)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-3)).right;
		Integer b = (Integer)((java_cup.runtime.Symbol) CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-3)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)).right;
		Integer c = (Integer)((java_cup.runtime.Symbol) CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).right;
		String d = (String)((java_cup.runtime.Symbol) CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$ClientParser$stack.peek()).value;
		 RESULT = new Err(a, b, c, d, e); 
              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("error_options",9, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-4)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // type ::= op_type TYPE_E cl_type 
            {
              String RESULT =null;
		int tokenleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).left;
		int tokenright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).right;
		Token token = (Token)((java_cup.runtime.Symbol) CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).value;
		 RESULT = token.getValue(); 
              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("type",0, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // line ::= op_line INTEGER cl_line 
            {
              Integer RESULT =null;
		int tokenleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).left;
		int tokenright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).right;
		Token token = (Token)((java_cup.runtime.Symbol) CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).value;
		 RESULT = Integer.valueOf(token.getValue()); 
              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("line",5, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // column ::= op_column INTEGER cl_column 
            {
              Integer RESULT =null;
		int tokenleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).left;
		int tokenright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).right;
		Token token = (Token)((java_cup.runtime.Symbol) CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).value;
		 RESULT = Integer.valueOf(token.getValue()); 
              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("column",6, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // lex ::= op_lex STR cl_lex 
            {
              String RESULT =null;
		int tokenleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).left;
		int tokenright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).right;
		Token token = (Token)((java_cup.runtime.Symbol) CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).value;
		 RESULT = token.getValue(); 
              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("lex",1, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // desc ::= op_desc STR cl_desc 
            {
              String RESULT =null;
		int tokenleft = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).left;
		int tokenright = ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).right;
		Token token = (Token)((java_cup.runtime.Symbol) CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-1)).value;
		 RESULT = token.getValue(); 
              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("desc",2, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // op_type ::= SMALLER TYPE GREATER 
            {
              Object RESULT =null;

              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("op_type",30, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // op_line ::= SMALLER LINE GREATER 
            {
              Object RESULT =null;

              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("op_line",31, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // op_column ::= SMALLER COLUMN GREATER 
            {
              Object RESULT =null;

              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("op_column",32, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // op_lex ::= SMALLER LEXEMA GREATER 
            {
              Object RESULT =null;

              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("op_lex",33, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // op_desc ::= SMALLER DESCRIPTION GREATER 
            {
              Object RESULT =null;

              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("op_desc",34, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // op_error ::= SMALLER ERROR GREATER 
            {
              Object RESULT =null;

              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("op_error",35, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // op_errors ::= SMALLER ERRORS GREATER 
            {
              Object RESULT =null;

              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("op_errors",36, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-2)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // cl_type ::= SMALLER DIVIDE TYPE GREATER 
            {
              Object RESULT =null;

              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("cl_type",37, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-3)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // cl_line ::= SMALLER DIVIDE LINE GREATER 
            {
              Object RESULT =null;

              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("cl_line",38, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-3)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // cl_column ::= SMALLER DIVIDE COLUMN GREATER 
            {
              Object RESULT =null;

              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("cl_column",39, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-3)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // cl_lex ::= SMALLER DIVIDE LEXEMA GREATER 
            {
              Object RESULT =null;

              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("cl_lex",40, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-3)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // cl_desc ::= SMALLER DIVIDE DESCRIPTION GREATER 
            {
              Object RESULT =null;

              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("cl_desc",41, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-3)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // cl_error ::= SMALLER DIVIDE ERROR GREATER 
            {
              Object RESULT =null;

              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("cl_error",42, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-3)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // cl_errors ::= SMALLER DIVIDE ERRORS GREATER 
            {
              Object RESULT =null;

              CUP$ClientParser$result = parser.getSymbolFactory().newSymbol("cl_errors",43, ((java_cup.runtime.Symbol)CUP$ClientParser$stack.elementAt(CUP$ClientParser$top-3)), ((java_cup.runtime.Symbol)CUP$ClientParser$stack.peek()), RESULT);
            }
          return CUP$ClientParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$ClientParser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$ClientParser$do_action(
    int                        CUP$ClientParser$act_num,
    java_cup.runtime.lr_parser CUP$ClientParser$parser,
    java.util.Stack            CUP$ClientParser$stack,
    int                        CUP$ClientParser$top)
    throws java.lang.Exception
    {
              return CUP$ClientParser$do_action_part00000000(
                               CUP$ClientParser$act_num,
                               CUP$ClientParser$parser,
                               CUP$ClientParser$stack,
                               CUP$ClientParser$top);
    }
}

}
