
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.cesar31.audiogeneratorclient.parser;

/** CUP generated class containing symbol constants. */
public class ClientParserSym {
  /* terminals */
  public static final int TYPE_E = 5;
  public static final int SMALLER = 25;
  public static final int EQUAL = 24;
  public static final int LIST = 15;
  public static final int DECIMAL = 29;
  public static final int COLUMN = 7;
  public static final int TRACK = 11;
  public static final int TRACKS = 10;
  public static final int ERROR = 3;
  public static final int GREATER = 26;
  public static final int EIGHTH = 23;
  public static final int NAME = 12;
  public static final int TRUE = 18;
  public static final int NOTE = 21;
  public static final int ERRORS = 2;
  public static final int TYPE = 4;
  public static final int LISTS = 14;
  public static final int DESCRIPTION = 9;
  public static final int RANDOM = 16;
  public static final int NUMBER = 22;
  public static final int EOF = 0;
  public static final int DIVIDE = 27;
  public static final int CHANNEL = 20;
  public static final int CIRCULAR = 17;
  public static final int DURATION = 13;
  public static final int FALSE = 19;
  public static final int error = 1;
  public static final int STR = 30;
  public static final int LINE = 6;
  public static final int INTEGER = 28;
  public static final int LEXEMA = 8;
  public static final int UNKNOWN = 31;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ERRORS",
  "ERROR",
  "TYPE",
  "TYPE_E",
  "LINE",
  "COLUMN",
  "LEXEMA",
  "DESCRIPTION",
  "TRACKS",
  "TRACK",
  "NAME",
  "DURATION",
  "LISTS",
  "LIST",
  "RANDOM",
  "CIRCULAR",
  "TRUE",
  "FALSE",
  "CHANNEL",
  "NOTE",
  "NUMBER",
  "EIGHTH",
  "EQUAL",
  "SMALLER",
  "GREATER",
  "DIVIDE",
  "INTEGER",
  "DECIMAL",
  "STR",
  "UNKNOWN"
  };
}

